services:
  postgres:
    #image: postgres:15
    build: . #Construir contenedor usando Dockerfile presente en el directorio actual (.)
    container_name: ContDBpractMod3 # Nombre del contenedor
    ports:
     - "5432:5432" # Puerto para conectar desde tu m치quina host al contenedor
    environment:
      POSTGRES_USER: Admin # Usuario de la base de datos
      POSTGRES_PASSWORD: p4ssw0rdDB # Contrase침a del usuario
      POSTGRES_DB: credenciales # Nombre de la base de datos
    volumes:
      # Espacio donde los datos se conservar치n, al detener el contenedor.
      - postgres_data:/var/lib/postgresql/data # Espacio donde los datos se conservar치n, al detener el contenedor.
volumes:
  postgres_data:
    driver: local
    